In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings("ignore")

from sklearn.linear_model import LogisticRegression
class LogitRegression():
  def __init__(self,learning_rate,iterations):
    self.learning_rate=learning_rate
    self.iterations=iterations
  def fit(self,X,Y):
    self.m,self.n=X.shape
    self.W=np.zeros(self.n)
    self.b=0
    self.X=X
    self.Y=Y

    for i in range(self.iterations):
      self.update_weights()
    return self

  def update_weights(self):
    A=1/(1+np.exp(-(self.X.dot(self.W)+self.b)))
    tmp=(A-self.Y.T)
    tmp=np.reshape(tmp,self.m)
    dW=np.dot(self.X.T,tmp)/self.m
    db=np.sum(tmp)/self.m

    self.W=self.W-self.learning_rate*dW
    self.b=self.b-self.learning_rate*db
    return self

  def predict( self, X ) :
        Z = 1 / (1+ np.exp(- (X.dot( self.W) + self.b ) ) )
        Y = np.where( Z> 0.5, 1, 0 )
        return Y,Z

In [2]:
df=pd.read_csv('diabetes.csv')
X=df.iloc[:,:-1].values
Y = df.iloc[:, -1:].values
# Splitting dataset into train and test set
X_train, X_test, Y_train, Y_test = train_test_split( X, Y, test_size = 1/3, random_state = 4 )
# Model training
model= LogitRegression(learning_rate= 0.01, iterations = 1000)
model.fit( X_train, Y_train )
model1 = LogisticRegression()
model1.fit( X_train, Y_train)
#Prediction on test set
Y_pred,Z_pred=model.predict( X_test )
Y_pred1 =model1.predict( X_test )

correctly_classified = 0
correctly_classified1 = 0

# counter
count = 0

for count in range( np.size(Y_pred ) ) :
    if Y_test[count] ==Y_pred[count] :
        correctly_classified = correctly_classified + 1
    if Y_test[count] == Y_pred1 [count] :
        correctly_classified1 = correctly_classified1 + 1
    count = count + 1
print("Accuracy on test set by our model  :",(correctly_classified / count ) * 100 ) 
print("Accuracy on test set by sklearn model   :",(correctly_classified1 / count ) * 100 )

Accuracy on test set by our model  : 47.22222222222222
Accuracy on test set by sklearn model   : 72.22222222222221


In [3]:
Y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0])

In [4]:
Z_pred

array([1.13283651e-08, 2.68278414e-21, 5.51206727e-08, 1.17426619e-16,
       1.90107875e-22, 1.55188536e-18, 3.28817430e-20, 2.56905569e-27,
       6.88498194e-21, 1.07704189e-18, 1.23462100e-05, 1.83223532e-17,
       9.98657696e-01, 1.49570099e-15, 3.33788132e-16, 1.08006672e-13,
       1.72732646e-17, 1.99043901e-05, 1.73890554e-14, 1.03219573e-11,
       1.53628834e-14, 1.12337807e-12, 3.35430031e-13, 1.22830308e-19,
       1.57822059e-08, 3.13587681e-13, 9.81641878e-01, 5.24645386e-15,
       9.99981268e-01, 1.25277468e-30, 2.12681374e-13, 9.99989615e-01,
       1.10614524e-11, 8.04633010e-07, 7.55961032e-12, 1.87557662e-22])

In [5]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score
from sklearn.metrics import log_loss

In [6]:
results=confusion_matrix(Y_test,Y_pred)
print('confusion matrix:')
print(results)

confusion matrix:
[[17  4]
 [15  0]]


In [7]:
print('Accuracy score is :',accuracy_score(Y_test,Y_pred))

Accuracy score is : 0.4722222222222222


In [8]:
print('classification report is :',classification_report(Y_test,Y_pred))

classification report is :               precision    recall  f1-score   support

           0       0.53      0.81      0.64        21
           1       0.00      0.00      0.00        15

    accuracy                           0.47        36
   macro avg       0.27      0.40      0.32        36
weighted avg       0.31      0.47      0.37        36



In [9]:
print('AUC-ROC :',roc_auc_score(Y_test,Y_pred))

AUC-ROC : 0.40476190476190477


In [10]:
print('logloss :',log_loss(Y_test,Y_pred))

logloss : 18.22888749702844
