In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [2]:
data = load_iris()

In [3]:
print('Classes to predict: ', data.target_names)

Classes to predict:  ['setosa' 'versicolor' 'virginica']


In [4]:
print('Features: ', data.feature_names)

Features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [5]:
X = data.data
y = data.target

In [6]:
display(X.shape, y.shape)

(150, 4)

(150,)

In [7]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 50, test_size = 0.25)

In [15]:
from sklearn.tree import DecisionTreeClassifier as DTC

In [11]:
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)

DecisionTreeClassifier()

In [12]:
y_pred = clf.predict(X_test)

In [13]:
from sklearn.metrics import accuracy_score

In [14]:
print('Accuracy using gini: ', accuracy_score(y_true=y_train, y_pred=clf.predict(X_train)))
print('Accuracy using gini: ', accuracy_score(y_true=y_test, y_pred=y_pred))

Accuracy using gini:  1.0
Accuracy using gini:  0.9473684210526315


In [16]:
clf_entropy = DTC(criterion= "entropy")

In [17]:
clf_entropy.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [18]:
y_pred_entropy = clf_entropy.predict(X_test)

In [21]:
print('Accuracy Score on train: ', accuracy_score(y_true=y_train, y_pred=clf_entropy.predict(X_train)))
print('Accuracy Score on test: ', accuracy_score(y_true=y_test, y_pred=y_pred))

Accuracy Score on train:  1.0
Accuracy Score on test:  0.9473684210526315


In [22]:
clf2 = DTC(min_samples_split = 50)
clf2.fit(X_train, y_train)

DecisionTreeClassifier(min_samples_split=50)

In [23]:
print('Accuracy Score on train: ', accuracy_score(y_true=y_train, y_pred=clf2.predict(X_train)))
print('Accuracy Score on test: ', accuracy_score(y_true=y_test, y_pred=y_pred))

Accuracy Score on train:  0.9642857142857143
Accuracy Score on test:  0.9473684210526315


In [24]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[11  0  0]
 [ 0 14  1]
 [ 0  1 11]]
